# Generated by Django 5.2.8 on 2025-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_siteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Poststraße 2–4, 53111 Bonn', max_length=255)),
                ('opening_hours', models.CharField(default='Montag bis Samstag, 11:00–20:30 Uhr', max_length=255)),
                ('phone', models.CharField(default='+49 228 88690432', max_length=100)),
                ('email', models.EmailField(default='info@kbg-europe.de', max_length=254)),
            ],
        ),
    ]
