# Generated by Django 5.2.8 on 2025-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('dish_id', models.CharField(blank=True, help_text="z.B. '1' oder '11'", max_length=10, verbose_name='Nummer')),
                ('name', models.CharField(max_length=200, verbose_name='Gericht Name')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Untertitel')),
                ('description_de', models.TextField(blank=True, verbose_name='Beschreibung DE')),
                ('description_en', models.TextField(blank=True, verbose_name='Beschreibung EN')),
                ('options_text', models.TextField(blank=True, help_text='Eine Option pro Zeile. Der Code (z.B. 1A) wird automatisch erkannt.', verbose_name='Optionen')),
                ('image', models.ImageField(upload_to='menu_items/', verbose_name='Gericht Bild')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='menu_bg/', verbose_name='Hintergrundbild')),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=50, verbose_name='Hintergrundfarbe (Hex)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
