# Generated by Django 5.2.8 on 2025-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='btn_lieferando_link',
            field=models.CharField(blank=True, default='https://lieferando.de', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_lieferando_text',
            field=models.CharField(default='Lieferando', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_pickup_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_pickup_text',
            field=models.CharField(default='Abholen', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_uber_link',
            field=models.CharField(blank=True, default='https://ubereats.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_uber_text',
            field=models.CharField(default='Uber Eats', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_wolt_link',
            field=models.CharField(blank=True, default='https://wolt.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='btn_wolt_text',
            field=models.CharField(default='Wolt', max_length=50),
        ),
    ]
