# Generated by Django 5.2.8 on 2025-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_type', models.CharField(max_length=50, verbose_name='Bewerbung für')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('cover_letter', models.FileField(upload_to='applications/cover_letters/', verbose_name='Anschreiben')),
                ('cv', models.FileField(upload_to='applications/cvs/', verbose_name='Lebenslauf')),
                ('status', models.CharField(choices=[('new', 'Neu / Unbearbeitet'), ('processed', 'Bearbeitet')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('manager', 'Shopleiter (m/w/d)'), ('service', 'Service (m/w/d)'), ('cook', 'Koch (m/w/d)')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/content/', verbose_name='Vorschaubild')),
                ('short_description', models.TextField(help_text='Jede Zeile ein Punkt.', verbose_name='Listenpunkte auf Karte')),
                ('popup_title', models.CharField(default='(Studentische) Aushilfskraft (m/w)', max_length=200, verbose_name='Popup Titel')),
                ('popup_text', models.TextField(help_text='Der Text im Popup links.', verbose_name='Popup Text (Anforderungen)')),
            ],
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
