# Generated by Django 5.2.8 on 2025-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_jobapplication_jobcontent_delete_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('title', models.CharField(default='Mitarbeiter (m/w/d)', max_length=200, verbose_name='Job Titel')),
                ('description', models.TextField(help_text='Jede neue Zeile wird ein Stichpunkt.', verbose_name='Beschreibung / Punkte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Vorschaubild')),
                ('button_link', models.CharField(default='mailto:jobs@kbg-europe.de', max_length=255, verbose_name='Link für Bewerbung')),
                ('button_text', models.CharField(default='Zur Bewerbung', max_length=50, verbose_name='Button Text')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='jobcontent',
            name='popup_text',
            field=models.TextField(blank=True, help_text='Der Text im Popup links.', verbose_name='Popup Text (Anforderungen)'),
        ),
        migrations.AlterField(
            model_name='jobcontent',
            name='short_description',
            field=models.TextField(blank=True, help_text='Jede Zeile ein Punkt.', verbose_name='Listenpunkte auf Karte'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dish_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nummer'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='options_text',
            field=models.TextField(blank=True, help_text='Eine Option pro Zeile.', verbose_name='Optionen'),
        ),
    ]
