# Generated by Django 5.2.8 on 2025-12-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
